dist: trusty
language: elixir
elixir: 1.5
otp_release: 20.0

env:
  global:
    - MIX_ENV=test

  matrix:
    - HEX_VERSION=master
    - HEX_VERSION=v0.14.1

matrix:
  include:
    - elixir: 1.3.4
      otp_release: 18.2

install:
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile

script:
  - mix test
  - mix credo --strict

after_success:
  - mix coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
